/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author YIJIA
 */
public class CountriesPage extends javax.swing.JFrame {
    
    private void loadCountries() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    try {
        java.sql.Connection conn = DBConnection.getConnection();
        String sql = "SELECT id, country_name FROM countries";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id"),
                rs.getString("country_name")
            };
            model.addRow(row);
        }

        rs.close();
        pst.close();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Load country failed: " + e.getMessage()
        );
    }
}

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CountriesPage.class.getName());
private javax.swing.DefaultListModel<String> listModel;
private javax.swing.JList<String> countryList;
private javax.swing.JButton viewBtn;
    /**
     * Creates new form CountriesPage
     */
    public CountriesPage() {
    initComponents();
    this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    loadFixedCountries(); 
}
    private void loadFixedCountries() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.setRowCount(0);

    model.addRow(new Object[]{1, "Taiwan"});
    model.addRow(new Object[]{2, "USA"});
    model.addRow(new Object[]{3, "Japan"});
    model.addRow(new Object[]{4, "Korea"});
    model.addRow(new Object[]{5, "China"});
    model.addRow(new Object[]{6, "Thailand"});
    model.addRow(new Object[]{7, "France"});
    model.addRow(new Object[]{8, "Italy"});
    model.addRow(new Object[]{9, "Spain"});
    model.addRow(new Object[]{10, "Mexico"});
    model.addRow(new Object[]{11, "India"});
    model.addRow(new Object[]{12, "Vietnam"});
    model.addRow(new Object[]{13, "Philippines"});
    model.addRow(new Object[]{14, "Germany"});
    model.addRow(new Object[]{15, "UK"});
    model.addRow(new Object[]{16, "Brazil"});
    model.addRow(new Object[]{17, "Argentina"});
    model.addRow(new Object[]{18, "Turkey"});
    model.addRow(new Object[]{19, "Indonesia"});
    model.addRow(new Object[]{20, "Malaysia"});
    model.addRow(new Object[]{21, "Singapore"});
    model.addRow(new Object[]{22, "Russia"});
    model.addRow(new Object[]{23, "Australia"});
    model.addRow(new Object[]{24, "New Zealand"});
    model.addRow(new Object[]{25, "Egypt"});
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Country"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {
        String country = jTable1.getValueAt(selectedRow, 1).toString();

        RecipesByCountryPage page = new RecipesByCountryPage(country);
        page.setVisible(true);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CountriesPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
